server:
  port: 8080

spring:
  application:
    name: bandlogs-manager
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/FREEPDB1
    username: SYSTEM
    password: $DB_PASSWORD
    driverClassName: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

jwt:
  secret: $SECRET_KEY

logging:
  level:
    org:
      springframework:
        jdbc: DEBUG