server:
  port: 8080

spring:
  application:
    name: bandlogs-manager
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/FREEPDB1
    username: SYSTEM
    password: 17609Br-15
    driverClassName: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

jwt:
  secret: MY_CU5T0M_B4NDL065_M4N463R_S3CR3T_K3Y

logging:
  level:
    org:
      springframework:
        jdbc: DEBUG
