server:
  port: 8080

spring:
  application:
    name: bandlogs-manager
  datasource:
    url: jdbc:h2:mem:bandlogsDatabase
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: true

jwt:
  secret: ${MY_SECRET}