server:
  port: 8080

spring:
  application:
    name: bandlogs-manager
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/FREEPDB1
    username: SYSTEM
    password: 2627036B-asdF
    driverClassName: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

jwt:
  secret: MY_0WN_CU5T0M_B4NDL065_S3CR3T_BY_Br4Nd0_4PP5

logging:
  level:
    org:
      springframework:
        jdbc: DEBUG